import '@styles/globals.scss'
import { fontMontserrat } from './fonts'
import ThemeProvider from './theme-provider'
import { AddressBar } from '@components/address-bar'
import { Providers as StoreProvider } from '@/redux/provider'
import { Locale, i18n } from '@i18n-config'
import Link from 'next/link'
import { getDictionary } from '@get-dictionary'

export const metadata = {
  title: 'Vua Thợ',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  modal,
  params,
}: {
  children: React.ReactNode
  modal: React.ReactNode
  params: { lang: Locale }
}) {
  const t = await getDictionary(params.lang)

  return (
    <html lang={params.lang} suppressHydrationWarning>
      <StoreProvider>
        <body
          className={`${fontMontserrat.className} min-h-screen overflow-y-scroll bg-white bg-[url('/images/grid.svg')] text-black dark:bg-black dark:text-white`}
        >
          <ThemeProvider
            themeProps={{ attribute: 'class', defaultTheme: 'light' }}
          >
            <div className=" container mx-auto">
              <div className="mx-auto max-w-4xl space-y-8 px-2 pt-20 lg:px-8 lg:py-8">
                <div className="bg-vc-border-gradient rounded-lg p-px shadow-lg shadow-black/20">
                  <div className="flex items-center gap-x-2 rounded-lg bg-black p-3.5 lg:px-5 lg:py-3">
                    <div className="rounded-lg bg-black">
                      <Link href="/auth/login">{t['login']}</Link>
                    </div>
                  </div>
                </div>
                <div className="bg-vc-border-gradient rounded-lg p-px shadow-lg shadow-black/20">
                  <div className="rounded-lg bg-black">
                    <AddressBar />
                  </div>
                </div>
                <div>{modal}</div>
                <div>{children}</div>
              </div>
            </div>
          </ThemeProvider>
        </body>
      </StoreProvider>
    </html>
  )
}
