import '@styles/globals.scss'
import { fontMontserrat } from './fonts'
import ThemeProvider from './theme-provider'
import { MuiThemeProvider } from './mui-setup'
import { AddressBar } from '@components/address-bar'
import { Providers } from '@/redux/provider'
import { i18n } from '@i18n-config'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default function RootLayout({
  children,
  modal,
  params,
}: {
  children: React.ReactNode
  modal: React.ReactNode
  params: { lang: string }
}) {
  return (
    <html lang={params.lang} className="dark test">
      <Providers>
        <body
          className={`${fontMontserrat.className} overflow-y-scroll bg-white bg-[url('/grid.svg')] text-black dark:bg-black dark:text-white`}
        >
          <ThemeProvider>
            <MuiThemeProvider>
              <div className=" container mx-auto">
                <div className="mx-auto max-w-4xl space-y-8 px-2 pt-20 lg:px-8 lg:py-8">
                  <div className="bg-vc-border-gradient rounded-lg p-px shadow-lg shadow-black/20">
                    <div className="rounded-lg bg-black">
                      <AddressBar />
                    </div>
                  </div>
                  <div>{modal}</div>
                  <div>{children}</div>
                </div>
              </div>
            </MuiThemeProvider>
          </ThemeProvider>
        </body>
      </Providers>
    </html>
  )
}
